### ISSUE TITLE
The file XiaomiOT.apk is missing

### ISSUE THREAD

**Issue by phuongnh13** [epodegrid/epd106-ADB#1]
Please re-upload XiaomiOT.apk. Thanks

**Comment by epodegrid** [comment]
Thank you for letting me know. I've reuploaded the files to MEGA to avoid any further problems. The XiaomiOT apk is available at [Mega Drive](https://mega.nz/file/zV5liQQZ#jAYeARU4YnnQmGo6AsLmRDf9x3T4DpmOIL5vJT_1MSg)

**Comment by phuongnh13** [comment]
Thank you for your quick support. Everything work fine for me!
