### ISSUE TITLE
Bootloader unlock

### ISSUE THREAD

**Issue by drago06** [epodegrid/epd106-ADB#5]
Hey. I think the bootloader is not locked at all. It lets me fastboot erase cache, meanwhile for exanple in my phone it doesn't saying that the bootloader is locked. If you wanna try flash a gsi, I don't know, maybe the phhusson's aosp 10 that is prerooted, so that you can merge boot, recovery and vbmeta out of it. I would also try fastboot erase userdata, and if it let you do that I think it would be almost sure that the bootloader is not locked. And if you want to, gimme ur email so that we can communicate without opening an issue on GitHub

**Comment by epodegrid** [comment]
This is great! I haven't tried it before. What does `fastboot oem device-info` return? I'll also give it a shot sometime later. I don't want to leave my email on a public domain, so can I pm it to you on reddit or something? Let me know what works for you!

**Comment by epodegrid** [comment]
Never mind, that didn't work. I also tried running `fastboot getvar all` but that's for MTK again. What is the fastboot command to check the bootloader status on Sunxi/Allwinner devices?

**Comment by drago06** [comment]
I have no idea of what is the command that you need to use to know the bootloader indo, I just think that you can be able to flash a gsi. Can you email me?
I managed to boot it to FEL mode and found that sunxi-tools sees it as a Onda v972 tablet. I do not know how to dump partitions tho. I tried to install FELix, another tool that can dump partitions, bit did not manage to install it. 
If you wanna help me out, email me here: leokol045@gmail.com
